name: pullrequest

on:
  pull_request:
    types: [opened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: "notify: new"
        if: github.event.pull_request.action == 'opened'
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "NEW PR ${{ github.event.pull_request.html_url }} by ${{ github.actor }} ${{ github.event.pull_request.title }}"
      - name: "notify: closed"
        if: github.event.pull_request.action == 'closed'
        uses: calamares/actions/matrix-notify@v4
        with:
          token: ${{ secrets.MATRIX_TOKEN }}
          room: ${{ secrets.MATRIX_ROOM }}
          message: "CLOSED ${{ github.event.pull_request.html_url }} by ${{ github.actor }} ${{ github.event.pull_request.title }}"
